server:
  port: 10000




spring:
  application:
    name: gateway-zuul-server
  zipkin:
    base-url: http://localhost:9411/



eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    max-per-route-connections: 200
    max-total-connections: 200

#网关路由配置
  #routes:
    #api-a:
      #path: /micro-user/**
      #serviceId: micro-user
    #baidu:
      #path: /it/**
      #url: http://www.ityouknow.com/


sidecar:
  port: 8000
  

      