server:
  port: 8091



spring:
  application:
    name: ribbon-client
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
