server:
  port: 8082
  
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8082/oauth2/user 
      #http://localhost:8082/me
    client:
      access-token-uri: http://localhost:8082/oauth2/oauth/token
      user-authorization-uri: http://localhost:8082/oauth2/oauth/authorize

      client-id: webapp
      #client-id:acme
      #client-secret: acmesecret
      
zuul:
  host:
    max-per-route-connections: 200
    max-total-connections: 200
  add-proxy-headers: true  
  routes:  
    oauth2: 
      path: /oauth2/**
      sensitiveHeaders:
      serviceId: oauth2-server
    resource:
      path: /resource/**
      url: http://localhost:8081/resource
      
            
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG


spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: oauth-ui

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/