server:
  port: 9999

security:
  ignored: /css/**,/style/**,/images/**,/js/**,/favicon.ico,/webjars/**,/user/company,/index.html

logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug

spring:
  datasource:
    url: jdbc:mysql://localhost/oauth
    username: root
    password: root
    tomcat:
      max-active: 200
  aop:
    proxy-target-class: true
  redis:
    host: localhost
    pool:
      max-active: 200
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: oauth2-server
management:
  context-path: /admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


