server:
  port: 10001

spring:
  application:
    name: dubbo-rpc-proxy
  dubbo:
    application:
      name : ${spring.application.name}
    registry:
      protocol : zookeeper
      address : localhost:2181
    consumer-config:
      timeout: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/