server:
  port: 8081
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/me

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
spring:
  application:
    name: resource-server
  zipkin:
    base-url: http://localhost:9411/


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/