server:
  port: 8080
spring:
  application:
    name: cloud-admin

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10

  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

